# frozen_string_literal: true

require "bundler/gem_tasks"
require "rake/extensiontask"

task build: :compile

GEMSPEC = Gem::Specification.load("atomic_counter.gemspec")

Rake::ExtensionTask.new("atomic_counter", GEMSPEC) do |ext|
  ext.lib_dir = "lib/atomic_counter"
end

task default: %i[clobber compile]
