# frozen_string_literal: true

require "bundler/gem_tasks"
require "rake/extensiontask"

task build: :compile

GEMSPEC = Gem::Specification.load("c_atomics.gemspec")

Rake::ExtensionTask.new("c_atomics", GEMSPEC) do |ext|
  ext.lib_dir = "lib/c_atomics"
end

task default: %i[clobber compile]
